version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: devops_user
      POSTGRES_PASSWORD: devops_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - APP_NAME=Sistema de Inventario DevOps
      - APP_VERSION=1.0.0
      - DB_HOST=db
      - DB_NAME=devops_db
      - DB_USER=devops_user
      - DB_PASSWORD=devops_password
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@devops.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data: